USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/meizu/mx5/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := mx5

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_BASE = 0x40078000

TARGET_NO_RADIOIMAGE := true
TARGET_PREBUILT_KERNEL := device/meizu/mx5/kernel
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x03f88000 --tags_offset 0x0df88000 --dt device/meizu/mx5/dt.img
KERNEL_EXFAT_MODULE_NAME := "exfat"
BOARD_DT_SIZE := 0
BOARD_SECOND_SIZE := 0
BOARD_SECOND_OFFSET := 00e88000


# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00380000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00480000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x08c60000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/meizu/mx5/kernel

BOARD_HAS_NO_SELECT_BUTTON := true

# Recovery
TARGET_RECOVERY_FSTAB := device/meizu/mx5/recovery.fstab
RECOVERY_FSTAB_VERSION := 2

# TWRP
RECOVERY_SDCARD_ON_DATA := true
TW_NO_REBOOT_BOOTLOADER := true
DEVICE_RESOLUTION := 1080x1920
